added tailwindCSS and tested it out on articles index page
kir-dev/schorpong-next pull request #30
Opened 2021-12-15 14:55 UTC by Tschonti

Closes #26

2021-12-15 22:36 UTC, SepsiLaszlo requested changes
Nice work, thank you for setting up TailwindCSS for the project! :dash: :leaves:  
I had one minor suggestion, but other than that it is all good! :+1:

2021-12-16 15:44 UTC, DannySS123 approved these changes

2021-12-17 08:40 UTC, SepsiLaszlo approved these changes

2021-12-19 14:14 UTC, poiuztrewq1 approved these changes
Nice work :100:

2021-12-19 14:14 UTC, merged